FROM openjdk:8-jre
LABEL role='openjdk' version='8' tags='jre8' description='openjdk jre8 based on debian'
#set enviroments
ENV TIMEZONE="Asia/Shanghai"
#install software
RUN cp -rf /usr/share/zoneinfo/"${TIMEZONE}" /etc/localtime && \
  echo "$TIMEZONE" > /etc/timezone
