FROM openjdk:8-jre-alpine
LABEL role='openjdk' version='8' tags='jre8' description='openjdk jre8 based on alpine'
#set enviroments
ENV TIMEZONE="Asia/Shanghai"
#install software
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update && \
#RUN apk update && \
  apk add tzdata && \
  cp -rf /usr/share/zoneinfo/"${TIMEZONE}" /etc/localtime && \
  echo "${TIMEZONE}" > /etc/timezone && \
  apk del tzdata && \
  rm -rf /var/cache/apk/* && \      
